import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/navigation/navigation";
import styles from "../styles/Home.module.css";
import Button from "react-bootstrap/Button";
import Link from "next/link";

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <h2 className="text-center mt-4">
          Professional Scrum Master I (PSM I) Practice Assessment
        </h2>
        <div className="grid justify-items-center">
          <Link href="/quiz">
            <Button variant="primary mt-4">Start Practice Assesment</Button>
          </Link>
        </div>
      </div>
    </>
  );
};

export default Home;
